[project]
name = 'monarchs'
version = '0.1.1'
description = 'A numerical model of ice shelf development'
requires-python = ">3.8"
authors = [
    {name = "Jon Elsey", email = "j.d.elsey@leeds.ac.uk"},
    {name = "Sammie Buzzard", email = 'sammie.buzzard@northumbria.ac.uk'}
]
readme = "README.md"
license = "GPL-3.0-or-later"
dependencies = [
    'numpy >= 1.26.3, < 2.0',
    'Numba >= 0.59',
    'scipy >= 1.12.0',
    'h5py',
    'netCDF4',
    'cartopy',
    'matplotlib',
    'Pillow',
    'imagecodecs',
    'pathos',
    'rioxarray',
    'rasterio',
    'pyproj',
    'dask',
]

classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]

mpi = [
    'mpi4py',
]
numba = [
    'NumbaMinpack',
]

[project.scripts]
monarchs = 'run_MONARCHS:monarchs'

[project.urls]
Repository = "https://github.com/monarchs-ice/MONARCHS"
Issues = "https://github.com/monarchs-ice/MONARCHS/issues"
Documentation = "https://monarchs-ice.github.io/monarchs/"
Homepage = "https://monarchs-ice.github.io/MONARCHS/"

[build-system]
build-backend = 'hatchling.build'
requires = ['hatchling']

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/monarchs"]
