# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      env:
        CMAKE_POLICY_VERSION_MINIMUM: "3.5"
      run: |
        python -m pip install --upgrade pip
        python -m pip install ruff pytest
        python -m pip install -e ".[numba]"

    - name: Check formatting with ruff
      run: |
        ruff format --check src/monarchs tests

    - name: Lint with ruff
      run: |
        ruff check src/monarchs tests

    - name: Test with pytest
      run: |
        cd tests/unit_tests
        pytest . 
        cd ../numba
        pytest .

